<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\n8Tracks.Application\n8Tracks.Application.csproj" />
    <ProjectReference Include="..\n8Tracks.Infrastructure\n8Tracks.Infrastructure.csproj" />
  </ItemGroup>

</Project>
