// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Fixture.Persistence.Migrations
{
    [DbContext(typeof(FixtureContext))]
    [Migration("20260101000000_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Fixture.Entry", b => { b.Property<string>("Key").HasDefaultValueSql("'{'"); });
#pragma warning restore 612, 618
        }
    }
}
