// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Fixture.Persistence.Migrations
{
    partial class Snapshot
    {
#pragma warning disable 612, 618
        void Build() { }
#pragma warning restore 612, 618
    }
}
