// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using n8Tracks.Infrastructure.Persistence;

#nullable disable

namespace n8Tracks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(N8TracksDbContext))]
    [Migration("20261006042112_AddAssets")]
    partial class AddAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AdministratorRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("UsernameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username_key");

                    b.HasKey("Id")
                        .HasName("pk_administrators");

                    b.HasIndex("Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_administrators_slot");

                    b.HasIndex("UsernameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_administrators_username_key");

                    b.ToTable("administrators", null, t =>
                        {
                            t.HasCheckConstraint("ck_administrators_slot", "slot = 1");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AlbumLinkRecord", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("TEXT")
                        .HasColumnName("album_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("AlbumId", "Position")
                        .HasName("pk_album_links");

                    b.ToTable("album_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_album_links_url", "url LIKE 'http://%' OR url LIKE 'https://%'");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AlbumRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbumArtistId")
                        .HasColumnType("TEXT")
                        .HasColumnName("album_artist_id");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT")
                        .HasColumnName("copyright");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("OriginalReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_release_date");

                    b.Property<string>("Publishing")
                        .HasColumnType("TEXT")
                        .HasColumnName("publishing");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_key");

                    b.Property<string>("Upc")
                        .HasColumnType("TEXT")
                        .HasColumnName("upc");

                    b.Property<string>("UpcKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("upc_key");

                    b.Property<string>("UpdatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("AlbumArtistId")
                        .HasDatabaseName("ix_albums_album_artist_id");

                    b.HasIndex("UpcKey")
                        .HasDatabaseName("ix_albums_upc_key");

                    b.HasIndex("TitleKey", "CreatedUtc")
                        .HasDatabaseName("ix_albums_title_key_created_utc");

                    b.ToTable("albums", null, t =>
                        {
                            t.HasCheckConstraint("ck_albums_title", "length(title) > 0");

                            t.HasCheckConstraint("ck_albums_upc", "upc IS NULL OR ((length(upc) = 12 OR length(upc) = 13) AND upc NOT GLOB '*[^0-9]*')");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AlbumSongRecord", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("TEXT")
                        .HasColumnName("album_id");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<int>("Disc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disc");

                    b.Property<int>("Track")
                        .HasColumnType("INTEGER")
                        .HasColumnName("track");

                    b.HasKey("AlbumId", "SongId")
                        .HasName("pk_album_songs");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_album_songs_song_id");

                    b.HasIndex("AlbumId", "Disc", "Track")
                        .IsUnique()
                        .HasDatabaseName("ix_album_songs_album_id_disc_track");

                    b.ToTable("album_songs", null, t =>
                        {
                            t.HasCheckConstraint("ck_album_songs_disc", "disc BETWEEN 1 AND 999");

                            t.HasCheckConstraint("ck_album_songs_track", "track BETWEEN 1 AND 999");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AppMetadataEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_metadata");

                    b.ToTable("app_metadata");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.ArtistAliasRecord", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT")
                        .HasColumnName("artist_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.HasKey("ArtistId", "Position")
                        .HasName("pk_artist_aliases");

                    b.HasIndex("NameKey")
                        .HasDatabaseName("ix_artist_aliases_name_key");

                    b.HasIndex("ArtistId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_artist_aliases_artist_id_name_key");

                    b.ToTable("artist_aliases", null, t =>
                        {
                            t.HasCheckConstraint("ck_artist_aliases_name", "length(name) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.ArtistLinkRecord", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT")
                        .HasColumnName("artist_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("ArtistId", "Position")
                        .HasName("pk_artist_links");

                    b.ToTable("artist_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_artist_links_url", "url LIKE 'http://%' OR url LIKE 'https://%'");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.ArtistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("UpdatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("NameKey", "CreatedUtc")
                        .HasDatabaseName("ix_artists_name_key_created_utc");

                    b.ToTable("artists", null, t =>
                        {
                            t.HasCheckConstraint("ck_artists_name", "length(name) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AssetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("media_type");

                    b.Property<string>("ThumbnailSizes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_sizes");

                    b.Property<string>("UploadedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_utc");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_content_hash");

                    b.HasIndex("UploadedUtc")
                        .HasDatabaseName("ix_assets_uploaded_utc");

                    b.ToTable("assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_assets_bytes", "bytes > 0");

                            t.HasCheckConstraint("ck_assets_dimensions", "width > 0 AND height > 0");

                            t.HasCheckConstraint("ck_assets_media_type", "media_type IN ('image/jpeg', 'image/png', 'image/webp')");

                            t.HasCheckConstraint("ck_assets_thumbnail_sizes_json", "json_valid(thumbnail_sizes) AND json_type(thumbnail_sizes) = 'array'");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.CredentialRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("LastUsedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("RevokedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_utc");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_name_key")
                        .HasFilter("revoked_utc IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_token_hash");

                    b.ToTable("credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_credentials_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_credentials_scopes", "length(scopes) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.EditorRevisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lyrics");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("Styles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("styles");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_editor_revisions");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_editor_revisions_sequence");

                    b.HasIndex("VersionId", "CreatedUtc", "Sequence")
                        .HasDatabaseName("ix_editor_revisions_version_id_created_utc_sequence");

                    b.ToTable("editor_revisions", (string)null);
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.GenerationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_generations");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_generations_song_id");

                    b.HasIndex("VersionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_generations_version_id_ordinal");

                    b.ToTable("generations", null, t =>
                        {
                            t.HasTrigger("tr_generations_identity_never_changes");

                            t.HasCheckConstraint("ck_generations_ordinal", "ordinal >= 1");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.GenreRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name_key");

                    b.ToTable("genres", null, t =>
                        {
                            t.HasCheckConstraint("ck_genres_name", "length(name) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.JobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("FinishedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_utc");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("FinishedUtc")
                        .HasDatabaseName("ix_jobs_finished_utc");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_sequence");

                    b.HasIndex("Status", "Sequence")
                        .HasDatabaseName("ix_jobs_status_sequence");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_payload_json", "payload IS NULL OR json_valid(payload)");

                            t.HasCheckConstraint("ck_jobs_progress", "progress BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_jobs_result_json", "result IS NULL OR json_valid(result)");

                            t.HasCheckConstraint("ck_jobs_status", "status IN ('queued', 'running', 'succeeded', 'failed')");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.PlaylistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_key");

                    b.Property<string>("UpdatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_playlists");

                    b.HasIndex("TitleKey", "CreatedUtc")
                        .HasDatabaseName("ix_playlists_title_key_created_utc");

                    b.ToTable("playlists", null, t =>
                        {
                            t.HasCheckConstraint("ck_playlists_title", "length(title) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.PlaylistSongRecord", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT")
                        .HasColumnName("playlist_id");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.HasKey("PlaylistId", "SongId")
                        .HasName("pk_playlist_songs");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_playlist_songs_song_id");

                    b.HasIndex("PlaylistId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_playlist_songs_playlist_id_position");

                    b.ToTable("playlist_songs", null, t =>
                        {
                            t.HasCheckConstraint("ck_playlist_songs_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.RelationshipTypeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<string>("ReverseName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reverse_name");

                    b.Property<string>("ReverseNameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reverse_name_key");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("SunoAction")
                        .HasColumnType("TEXT")
                        .HasColumnName("suno_action");

                    b.HasKey("Id")
                        .HasName("pk_song_relationship_types");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_song_relationship_types_name_key");

                    b.HasIndex("ReverseNameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_song_relationship_types_reverse_name_key");

                    b.ToTable("song_relationship_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_song_relationship_types_names", "length(name) > 0 AND length(reverse_name) > 0");

                            t.HasCheckConstraint("ck_song_relationship_types_suno_action", "suno_action IS NULL OR is_system = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a10a6e-de00-7000-8000-000000000001"),
                            IsSystem = true,
                            Name = "Cover",
                            NameKey = "COVER",
                            ReverseName = "Covered by",
                            ReverseNameKey = "COVERED BY",
                            Revision = 1,
                            SunoAction = "cover"
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-de01-7001-8000-000000000002"),
                            IsSystem = true,
                            Name = "Extend",
                            NameKey = "EXTEND",
                            ReverseName = "Extended by",
                            ReverseNameKey = "EXTENDED BY",
                            Revision = 1,
                            SunoAction = "extend"
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-de02-7002-8000-000000000003"),
                            IsSystem = true,
                            Name = "Reuse Prompt",
                            NameKey = "REUSE PROMPT",
                            ReverseName = "Prompt reused by",
                            ReverseNameKey = "PROMPT REUSED BY",
                            Revision = 1,
                            SunoAction = "reuse_prompt"
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-de03-7003-8000-000000000004"),
                            IsSystem = true,
                            Name = "Mashup",
                            NameKey = "MASHUP",
                            ReverseName = "Used in mashup",
                            ReverseNameKey = "USED IN MASHUP",
                            Revision = 1,
                            SunoAction = "mashup"
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-de04-7004-8000-000000000005"),
                            IsSystem = true,
                            Name = "Sample This Song",
                            NameKey = "SAMPLE THIS SONG",
                            ReverseName = "Sampled by",
                            ReverseNameKey = "SAMPLED BY",
                            Revision = 1,
                            SunoAction = "sample"
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-de05-7005-8000-000000000006"),
                            IsSystem = true,
                            Name = "Use as Inspiration",
                            NameKey = "USE AS INSPIRATION",
                            ReverseName = "Inspired",
                            ReverseNameKey = "INSPIRED",
                            Revision = 1,
                            SunoAction = "inspiration"
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-de06-7006-8000-000000000007"),
                            IsSystem = true,
                            Name = "Voice",
                            NameKey = "VOICE",
                            ReverseName = "Voice used by",
                            ReverseNameKey = "VOICE USED BY",
                            Revision = 1,
                            SunoAction = "voice"
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-de07-7007-8000-000000000008"),
                            IsSystem = true,
                            Name = "Remix",
                            NameKey = "REMIX",
                            ReverseName = "Remixed by",
                            ReverseNameKey = "REMIXED BY",
                            Revision = 1
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-de08-7008-8000-000000000009"),
                            IsSystem = true,
                            Name = "Derived From",
                            NameKey = "DERIVED FROM",
                            ReverseName = "Source of",
                            ReverseNameKey = "SOURCE OF",
                            Revision = 1
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Property<string>("IdHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_hash");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("administrator_id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("LastUsedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_utc");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.HasKey("IdHash")
                        .HasName("pk_sessions");

                    b.HasIndex("AdministratorId")
                        .HasDatabaseName("ix_sessions_administrator_id");

                    b.HasIndex("LastUsedUtc")
                        .HasDatabaseName("ix_sessions_last_used_utc");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SettingRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_value_json", "json_valid(value)");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.ShortcodeSequenceRecord", b =>
                {
                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<long>("LastValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_value");

                    b.HasKey("Slot")
                        .HasName("pk_shortcode_sequence");

                    b.ToTable("shortcode_sequence", null, t =>
                        {
                            t.HasCheckConstraint("ck_shortcode_sequence_last_value", "last_value >= 0");

                            t.HasCheckConstraint("ck_shortcode_sequence_slot", "slot = 1");
                        });

                    b.HasData(
                        new
                        {
                            Slot = 1,
                            LastValue = 0L
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongCreditRecord", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT")
                        .HasColumnName("artist_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("SongId", "ArtistId")
                        .HasName("pk_song_artist_credits");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_song_artist_credits_artist_id");

                    b.HasIndex("SongId", "Role", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_song_artist_credits_song_id_role_position");

                    b.ToTable("song_artist_credits", null, t =>
                        {
                            t.HasCheckConstraint("ck_song_artist_credits_role", "(role = 'primary' AND position = 0) OR (role = 'featured' AND position >= 0)");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongGenreRecord", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT")
                        .HasColumnName("genre_id");

                    b.HasKey("SongId", "GenreId")
                        .HasName("pk_song_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_song_genres_genre_id");

                    b.ToTable("song_genres", (string)null);
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongLinkRecord", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("SongId", "Position")
                        .HasName("pk_song_links");

                    b.ToTable("song_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_song_links_url", "url LIKE 'http://%' OR url LIKE 'https://%'");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Concept")
                        .HasColumnType("TEXT")
                        .HasColumnName("concept");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT")
                        .HasColumnName("copyright");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_version_id");

                    b.Property<string>("ExplicitContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("explicit_content");

                    b.Property<string>("Isrc")
                        .HasColumnType("TEXT")
                        .HasColumnName("isrc");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_release_date");

                    b.Property<string>("Publishing")
                        .HasColumnType("TEXT")
                        .HasColumnName("publishing");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<long>("ShortcodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shortcode_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_key");

                    b.Property<string>("TitleSortKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_sort_key");

                    b.Property<string>("UpdatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_state_id");

                    b.HasKey("Id")
                        .HasName("pk_songs");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_songs_current_version_id");

                    b.HasIndex("Isrc")
                        .HasDatabaseName("ix_songs_isrc");

                    b.HasIndex("ShortcodeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_songs_shortcode_number");

                    b.HasIndex("TitleKey")
                        .HasDatabaseName("ix_songs_title_key");

                    b.HasIndex("WorkflowStateId")
                        .HasDatabaseName("ix_songs_workflow_state_id");

                    b.HasIndex("TitleSortKey", "ShortcodeNumber")
                        .HasDatabaseName("ix_songs_title_sort_key_shortcode_number");

                    b.HasIndex("UpdatedUtc", "ShortcodeNumber")
                        .HasDatabaseName("ix_songs_updated_utc_shortcode_number");

                    b.ToTable("songs", null, t =>
                        {
                            t.HasCheckConstraint("ck_songs_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_songs_shortcode_number", "shortcode_number >= 1");

                            t.HasCheckConstraint("ck_songs_title", "length(title) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongRelationshipRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("FromSongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("from_song_id");

                    b.Property<Guid>("ToSongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("to_song_id");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_song_relationships");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_song_relationships_type_id");

                    b.HasIndex("FromSongId", "TypeId")
                        .HasDatabaseName("ix_song_relationships_from_song_id_type_id");

                    b.HasIndex("ToSongId", "TypeId")
                        .HasDatabaseName("ix_song_relationships_to_song_id_type_id");

                    b.ToTable("song_relationships", null, t =>
                        {
                            t.HasCheckConstraint("ck_song_relationships_two_songs", "from_song_id <> to_song_id");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongTagRecord", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_id");

                    b.HasKey("SongId", "TagId")
                        .HasName("pk_song_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_song_tags_tag_id");

                    b.ToTable("song_tags", (string)null);
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SunoModelRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Discovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discovered");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<bool>("Retired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retired");

                    b.HasKey("Id")
                        .HasName("pk_suno_models");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_suno_models_name_key");

                    b.HasIndex("Position")
                        .IsUnique()
                        .HasDatabaseName("ix_suno_models_position");

                    b.ToTable("suno_models", null, t =>
                        {
                            t.HasCheckConstraint("ck_suno_models_name", "length(name) > 0");

                            t.HasCheckConstraint("ck_suno_models_position", "position >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a10a6e-dd00-7000-8000-000000000001"),
                            Discovered = false,
                            Name = "v6",
                            NameKey = "V6",
                            Position = 1,
                            Retired = false
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dd01-7001-8000-000000000002"),
                            Discovered = false,
                            Name = "v6-wild",
                            NameKey = "V6-WILD",
                            Position = 2,
                            Retired = false
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dd02-7002-8000-000000000003"),
                            Discovered = false,
                            Name = "v6-mini",
                            NameKey = "V6-MINI",
                            Position = 3,
                            Retired = false
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.TagRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("colour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name_key");

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_tags_colour", "colour IN ('gray', 'red', 'pink', 'grape', 'violet', 'indigo', 'blue', 'cyan', 'teal', 'green', 'yellow', 'orange')");

                            t.HasCheckConstraint("ck_tags_name", "length(name) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.UsedVersionNumberRecord", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.HasKey("SongId", "Number")
                        .HasName("pk_used_version_numbers");

                    b.ToTable("used_version_numbers", null, t =>
                        {
                            t.HasCheckConstraint("ck_used_version_numbers_number", "length(number) BETWEEN 1 AND 64");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.VersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("inputs");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_frozen");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<int>("LastGenerationOrdinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_generation_ordinal");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lyrics");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.Property<string>("NumberSortKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("number_sort_key");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<string>("Styles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("styles");

                    b.Property<string>("UpdatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_versions");

                    b.HasIndex("SongId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_versions_song_id_number");

                    b.HasIndex("SongId", "NumberSortKey")
                        .HasDatabaseName("ix_versions_song_id_number_sort_key");

                    b.ToTable("versions", null, t =>
                        {
                            t.HasTrigger("tr_versions_frozen_inputs_never_change");

                            t.HasTrigger("tr_versions_number_never_changes");

                            t.HasTrigger("tr_versions_record_number_after_insert");

                            t.HasTrigger("tr_versions_touch_song_after_insert");

                            t.HasTrigger("tr_versions_touch_song_after_update");

                            t.HasCheckConstraint("ck_versions_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_versions_visibility", "visibility IN ('active', 'archived')");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.WorkflowStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("colour");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_workflow_states");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_states_name_key");

                    b.HasIndex("Position")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_states_position");

                    b.ToTable("workflow_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_workflow_states_name", "length(name) > 0");

                            t.HasCheckConstraint("ck_workflow_states_position", "position >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a10a6e-dc80-7000-8000-000000000001"),
                            Colour = "yellow",
                            Hidden = false,
                            Name = "Idea",
                            NameKey = "IDEA",
                            Position = 1
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc81-7001-8000-000000000002"),
                            Colour = "blue",
                            Hidden = false,
                            Name = "Writing",
                            NameKey = "WRITING",
                            Position = 2
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc82-7002-8000-000000000003"),
                            Colour = "violet",
                            Hidden = false,
                            Name = "Generating",
                            NameKey = "GENERATING",
                            Position = 3
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc83-7003-8000-000000000004"),
                            Colour = "orange",
                            Hidden = false,
                            Name = "Refining",
                            NameKey = "REFINING",
                            Position = 4
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc84-7004-8000-000000000005"),
                            Colour = "green",
                            Hidden = false,
                            Name = "Final",
                            NameKey = "FINAL",
                            Position = 5
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc85-7005-8000-000000000006"),
                            Colour = "teal",
                            Hidden = false,
                            Name = "Released",
                            NameKey = "RELEASED",
                            Position = 6
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc86-7006-8000-000000000007"),
                            Colour = "gray",
                            Hidden = false,
                            Name = "Archived",
                            NameKey = "ARCHIVED",
                            Position = 7
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Retention.PendingFileDeletionRecord", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<string>("LastAttemptUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_attempt_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("QueuedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("queued_utc");

                    b.HasKey("Path")
                        .HasName("pk_pending_file_deletions");

                    b.ToTable("pending_file_deletions", (string)null);
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Retention.RetentionGroupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DeletedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_utc");

                    b.Property<string>("Files")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("files");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("PruneAfterUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prune_after_utc");

                    b.Property<string>("Shortcode")
                        .HasColumnType("TEXT")
                        .HasColumnName("shortcode");

                    b.HasKey("Id")
                        .HasName("pk_retention_groups");

                    b.HasIndex("PruneAfterUtc")
                        .HasDatabaseName("ix_retention_groups_prune_after_utc");

                    b.HasIndex("Shortcode")
                        .HasDatabaseName("ix_retention_groups_shortcode");

                    b.ToTable("retention_groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_retention_groups_files_json", "json_valid(files) AND json_type(files) = 'array'");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Retention.RetentionRecordRecord", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("original_id");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("record_type");

                    b.Property<int>("ShapeVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shape_version");

                    b.HasKey("GroupId", "Position")
                        .HasName("pk_retention_records");

                    b.HasIndex("RecordType", "OriginalId")
                        .HasDatabaseName("ix_retention_records_record_type_original_id");

                    b.ToTable("retention_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_retention_records_document_json", "json_valid(document) AND json_type(document) = 'object'");

                            t.HasCheckConstraint("ck_retention_records_shape_version", "shape_version >= 1");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AlbumLinkRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.AlbumRecord", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_links_albums_album_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AlbumRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.ArtistRecord", null)
                        .WithMany()
                        .HasForeignKey("AlbumArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_albums_artists_album_artist_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AlbumSongRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.AlbumRecord", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_songs_albums_album_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_songs_songs_song_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.ArtistAliasRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.ArtistRecord", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_aliases_artists_artist_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.ArtistLinkRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.ArtistRecord", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_links_artists_artist_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.EditorRevisionRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.VersionRecord", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editor_revisions_versions_version_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.GenerationRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_generations_songs_song_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.VersionRecord", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_generations_versions_version_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.PlaylistSongRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.PlaylistRecord", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_songs_playlists_playlist_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_songs_songs_song_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.AdministratorRecord", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_administrators_administrator_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongCreditRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.ArtistRecord", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_artist_credits_artists_artist_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_artist_credits_songs_song_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongGenreRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.GenreRecord", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_genres_genres_genre_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_genres_songs_song_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongLinkRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_links_songs_song_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.VersionRecord", null)
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_songs_versions_current_version_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.WorkflowStateRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_songs_workflow_states_workflow_state_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongRelationshipRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("FromSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_relationships_songs_from_song_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("ToSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_relationships_songs_to_song_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.RelationshipTypeRecord", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_relationships_song_relationship_types_type_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongTagRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_tags_songs_song_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.TagRecord", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_tags_tags_tag_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.UsedVersionNumberRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_used_version_numbers_songs_song_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.VersionRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versions_songs_song_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Retention.RetentionRecordRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Retention.RetentionGroupRecord", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retention_records_retention_groups_group_id");
                });
#pragma warning restore 612, 618
        }
    }
}
