// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using n8Tracks.Infrastructure.Persistence;

#nullable disable

namespace n8Tracks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(N8TracksDbContext))]
    [Migration("20261005163000_AddSpeechAndSoundInputs")]
    partial class AddSpeechAndSoundInputs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AdministratorRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("UsernameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username_key");

                    b.HasKey("Id")
                        .HasName("pk_administrators");

                    b.HasIndex("Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_administrators_slot");

                    b.HasIndex("UsernameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_administrators_username_key");

                    b.ToTable("administrators", null, t =>
                        {
                            t.HasCheckConstraint("ck_administrators_slot", "slot = 1");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AppMetadataEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_metadata");

                    b.ToTable("app_metadata");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.CredentialRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("LastUsedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("RevokedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_utc");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_name_key")
                        .HasFilter("revoked_utc IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_token_hash");

                    b.ToTable("credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_credentials_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_credentials_scopes", "length(scopes) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.EditorRevisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lyrics");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("Styles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("styles");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_editor_revisions");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_editor_revisions_sequence");

                    b.HasIndex("VersionId", "CreatedUtc", "Sequence")
                        .HasDatabaseName("ix_editor_revisions_version_id_created_utc_sequence");

                    b.ToTable("editor_revisions", (string)null);
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.GenerationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_generations");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_generations_song_id");

                    b.HasIndex("VersionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_generations_version_id_ordinal");

                    b.ToTable("generations", null, t =>
                        {
                            t.HasTrigger("tr_generations_identity_never_changes");

                            t.HasCheckConstraint("ck_generations_ordinal", "ordinal >= 1");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.JobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("FinishedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_utc");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("FinishedUtc")
                        .HasDatabaseName("ix_jobs_finished_utc");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_sequence");

                    b.HasIndex("Status", "Sequence")
                        .HasDatabaseName("ix_jobs_status_sequence");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_payload_json", "payload IS NULL OR json_valid(payload)");

                            t.HasCheckConstraint("ck_jobs_progress", "progress BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_jobs_result_json", "result IS NULL OR json_valid(result)");

                            t.HasCheckConstraint("ck_jobs_status", "status IN ('queued', 'running', 'succeeded', 'failed')");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Property<string>("IdHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_hash");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("administrator_id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("LastUsedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_utc");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.HasKey("IdHash")
                        .HasName("pk_sessions");

                    b.HasIndex("AdministratorId")
                        .HasDatabaseName("ix_sessions_administrator_id");

                    b.HasIndex("LastUsedUtc")
                        .HasDatabaseName("ix_sessions_last_used_utc");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SettingRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_value_json", "json_valid(value)");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.ShortcodeSequenceRecord", b =>
                {
                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<long>("LastValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_value");

                    b.HasKey("Slot")
                        .HasName("pk_shortcode_sequence");

                    b.ToTable("shortcode_sequence", null, t =>
                        {
                            t.HasCheckConstraint("ck_shortcode_sequence_last_value", "last_value >= 0");

                            t.HasCheckConstraint("ck_shortcode_sequence_slot", "slot = 1");
                        });

                    b.HasData(
                        new
                        {
                            Slot = 1,
                            LastValue = 0L
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Concept")
                        .HasColumnType("TEXT")
                        .HasColumnName("concept");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_version_id");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<long>("ShortcodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shortcode_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TitleSortKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_sort_key");

                    b.Property<string>("UpdatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_state_id");

                    b.HasKey("Id")
                        .HasName("pk_songs");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_songs_current_version_id");

                    b.HasIndex("ShortcodeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_songs_shortcode_number");

                    b.HasIndex("WorkflowStateId")
                        .HasDatabaseName("ix_songs_workflow_state_id");

                    b.HasIndex("TitleSortKey", "ShortcodeNumber")
                        .HasDatabaseName("ix_songs_title_sort_key_shortcode_number");

                    b.HasIndex("UpdatedUtc", "ShortcodeNumber")
                        .HasDatabaseName("ix_songs_updated_utc_shortcode_number");

                    b.ToTable("songs", null, t =>
                        {
                            t.HasCheckConstraint("ck_songs_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_songs_shortcode_number", "shortcode_number >= 1");

                            t.HasCheckConstraint("ck_songs_title", "length(title) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.UsedVersionNumberRecord", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.HasKey("SongId", "Number")
                        .HasName("pk_used_version_numbers");

                    b.ToTable("used_version_numbers", null, t =>
                        {
                            t.HasCheckConstraint("ck_used_version_numbers_number", "length(number) BETWEEN 1 AND 64");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.VersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("inputs");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_frozen");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<int>("LastGenerationOrdinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_generation_ordinal");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lyrics");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.Property<string>("NumberSortKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("number_sort_key");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<string>("Styles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("styles");

                    b.Property<string>("UpdatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_versions");

                    b.HasIndex("SongId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_versions_song_id_number");

                    b.HasIndex("SongId", "NumberSortKey")
                        .HasDatabaseName("ix_versions_song_id_number_sort_key");

                    b.ToTable("versions", null, t =>
                        {
                            t.HasTrigger("tr_versions_frozen_inputs_never_change");

                            t.HasTrigger("tr_versions_number_never_changes");

                            t.HasTrigger("tr_versions_record_number_after_insert");

                            t.HasTrigger("tr_versions_touch_song_after_insert");

                            t.HasTrigger("tr_versions_touch_song_after_update");

                            t.HasCheckConstraint("ck_versions_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_versions_visibility", "visibility IN ('active', 'archived')");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.WorkflowStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("colour");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_workflow_states");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_states_name_key");

                    b.HasIndex("Position")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_states_position");

                    b.ToTable("workflow_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_workflow_states_name", "length(name) > 0");

                            t.HasCheckConstraint("ck_workflow_states_position", "position >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a10a6e-dc80-7000-8000-000000000001"),
                            Colour = "yellow",
                            Hidden = false,
                            Name = "Idea",
                            NameKey = "IDEA",
                            Position = 1
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc81-7001-8000-000000000002"),
                            Colour = "blue",
                            Hidden = false,
                            Name = "Writing",
                            NameKey = "WRITING",
                            Position = 2
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc82-7002-8000-000000000003"),
                            Colour = "violet",
                            Hidden = false,
                            Name = "Generating",
                            NameKey = "GENERATING",
                            Position = 3
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc83-7003-8000-000000000004"),
                            Colour = "orange",
                            Hidden = false,
                            Name = "Refining",
                            NameKey = "REFINING",
                            Position = 4
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc84-7004-8000-000000000005"),
                            Colour = "green",
                            Hidden = false,
                            Name = "Final",
                            NameKey = "FINAL",
                            Position = 5
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc85-7005-8000-000000000006"),
                            Colour = "teal",
                            Hidden = false,
                            Name = "Released",
                            NameKey = "RELEASED",
                            Position = 6
                        },
                        new
                        {
                            Id = new Guid("01a10a6e-dc86-7006-8000-000000000007"),
                            Colour = "gray",
                            Hidden = false,
                            Name = "Archived",
                            NameKey = "ARCHIVED",
                            Position = 7
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.EditorRevisionRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.VersionRecord", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editor_revisions_versions_version_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.GenerationRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_generations_songs_song_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.VersionRecord", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_generations_versions_version_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.AdministratorRecord", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_administrators_administrator_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SongRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.VersionRecord", null)
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_songs_versions_current_version_id");

                    b.HasOne("n8Tracks.Infrastructure.Persistence.WorkflowStateRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_songs_workflow_states_workflow_state_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.UsedVersionNumberRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_used_version_numbers_songs_song_id");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.VersionRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.SongRecord", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versions_songs_song_id");
                });
#pragma warning restore 612, 618
        }
    }
}
