// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using n8Tracks.Infrastructure.Persistence;

#nullable disable

namespace n8Tracks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(N8TracksDbContext))]
    [Migration("20261005071707_AddJobs")]
    partial class AddJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AdministratorRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("UsernameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username_key");

                    b.HasKey("Id")
                        .HasName("pk_administrators");

                    b.HasIndex("Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_administrators_slot");

                    b.HasIndex("UsernameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_administrators_username_key");

                    b.ToTable("administrators", null, t =>
                        {
                            t.HasCheckConstraint("ck_administrators_slot", "slot = 1");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AppMetadataEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_metadata");

                    b.ToTable("app_metadata");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.CredentialRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("LastUsedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_key");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("RevokedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_utc");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_name_key")
                        .HasFilter("revoked_utc IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_token_hash");

                    b.ToTable("credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_credentials_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_credentials_scopes", "length(scopes) > 0");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.JobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("FinishedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_utc");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("FinishedUtc")
                        .HasDatabaseName("ix_jobs_finished_utc");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_sequence");

                    b.HasIndex("Status", "Sequence")
                        .HasDatabaseName("ix_jobs_status_sequence");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_payload_json", "payload IS NULL OR json_valid(payload)");

                            t.HasCheckConstraint("ck_jobs_progress", "progress BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_jobs_result_json", "result IS NULL OR json_valid(result)");

                            t.HasCheckConstraint("ck_jobs_status", "status IN ('queued', 'running', 'succeeded', 'failed')");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Property<string>("IdHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_hash");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("administrator_id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("LastUsedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_utc");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.HasKey("IdHash")
                        .HasName("pk_sessions");

                    b.HasIndex("AdministratorId")
                        .HasDatabaseName("ix_sessions_administrator_id");

                    b.HasIndex("LastUsedUtc")
                        .HasDatabaseName("ix_sessions_last_used_utc");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SettingRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_value_json", "json_valid(value)");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.HasOne("n8Tracks.Infrastructure.Persistence.AdministratorRecord", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_administrators_administrator_id");
                });
#pragma warning restore 612, 618
        }
    }
}
