// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using n8Tracks.Infrastructure.Persistence;

#nullable disable

namespace n8Tracks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(N8TracksDbContext))]
    [Migration("20261005050301_AddAdministratorsAndSettings")]
    partial class AddAdministratorsAndSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AdministratorRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("UsernameKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username_key");

                    b.HasKey("Id")
                        .HasName("pk_administrators");

                    b.HasIndex("Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_administrators_slot");

                    b.HasIndex("UsernameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_administrators_username_key");

                    b.ToTable("administrators", null, t =>
                        {
                            t.HasCheckConstraint("ck_administrators_slot", "slot = 1");
                        });
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.AppMetadataEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_metadata");

                    b.ToTable("app_metadata");
                });

            modelBuilder.Entity("n8Tracks.Infrastructure.Persistence.SettingRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_value_json", "json_valid(value)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
