#!/usr/bin/env python3
"""Invariant 8 guard, rationale half: every warning suppression carries a one-line rationale.

Usage: check-suppressions.py [ROOT]

Scans the git-tracked files under ROOT (default: the repository this script lives in) and prints
one line per suppression that has no rationale:

    <file>:<line>: <what was found>

Exit code 0 when there is none (and nothing is printed), 1 when there is at least one, 2 for a
usage error. Run it through scripts/check-suppressions.sh.

The pattern list is closed. A new kind of switch-off is added here together with a fixture pair
under scripts/tests/check-suppressions/fixtures/.

What is a suppression, and where its rationale may stand:

  C# (.cs)
    #pragma warning disable, #nullable disable   a // comment on the same or the preceding line
    [SuppressMessage], [UnconditionalSuppressMessage]
                                                 a Justification string, or a comment as above
  MSBuild (.csproj, .props, .targets)
    <NoWarn>, <WarningsNotAsErrors>, and the same names as attributes (NoWarn on a
    PackageReference)                            an XML comment on the same or the preceding line
  .editorconfig, .globalconfig
    a severity of none, silent, or suggestion    a # or ; comment on the same or the preceding line
  JavaScript and TypeScript (.ts .tsx .mts .cts .js .jsx .mjs .cjs)
    eslint-disable, eslint-disable-line, eslint-disable-next-line, and an inline
    /* eslint rule: off */ comment               a trailing "-- reason" only
    @ts-ignore, @ts-expect-error, @ts-nocheck    text after the directive, or a comment on the
                                                 preceding line
  ESLint configuration (eslint.config.*, .eslintrc.js, .eslintrc.cjs)
    a rule set to 'off' or 0, and each use of eslint-config-prettier or disableTypeChecked
                                                 a comment on the same or the preceding line

A rationale is at least ten characters and is not a placeholder (TODO, FIXME, pending, n/a,
<Pending>, a bare "--"). A preceding line that is itself a suppression explains nothing. A comment
that runs over several lines counts as a whole.

Not scanned: files under bin/, obj/, node_modules/, and dist/; this script's own fixtures when a
tree that contains them is scanned; and EF Core's generated files, which are the .cs files under a
Migrations folder that carry the "<auto-generated" header.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys

FIXTURES = "scripts/tests/check-suppressions/"
SKIPPED_DIRECTORIES = {"bin", "obj", "node_modules", "dist"}

CSHARP = (".cs",)
MSBUILD = (".csproj", ".props", ".targets")
ANALYZER_CONFIG = (".editorconfig", ".globalconfig")
SCRIPT = (".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs")
ESLINT_CONFIG = re.compile(r"^(eslint\.config\.(js|mjs|cjs|ts|mts|cts)|\.eslintrc\.(js|cjs))$")

MINIMUM_RATIONALE_LENGTH = 10
PLACEHOLDER = re.compile(r"^(todo|fixme|pending|n/a)", re.IGNORECASE)


def is_rationale(text: str) -> bool:
    """True when the text explains something: long enough, and not a placeholder."""
    # Leading punctuation ("-- ", ": ", "<") is decoration, not explanation.
    stripped = re.sub(r"^[^0-9A-Za-z]+", "", text.strip()).rstrip()
    if len(stripped) < MINIMUM_RATIONALE_LENGTH:
        return False
    return not PLACEHOLDER.match(stripped)


# --------------------------------------------------------------------------------------------
# C-style sources (C#, JavaScript, TypeScript)
# --------------------------------------------------------------------------------------------

ESLINT_DISABLE = re.compile(r"(?://|/\*)\s*eslint-disable(?:-next-line|-line)?(?![\w-])")
ESLINT_INLINE = re.compile(r"/\*\s*eslint\s+(?!-)")
TS_DIRECTIVE = re.compile(r"(?://+|/\*+)\s*@ts-(ignore|expect-error|nocheck)(?![\w-])")
PRAGMA_DISABLE = re.compile(r"^\s*#\s*pragma\s+warning\s+disable\b")
NULLABLE_DISABLE = re.compile(r"^\s*#\s*nullable\s+disable\b")
SUPPRESS_MESSAGE = re.compile(r"\b(?:Unconditional)?SuppressMessage(?:Attribute)?\s*\(")
SWITCHED_OFF = re.compile(r"""(?:(['"`])off\1|(?<![\w.])0(?![\w.]))""")


def is_c_directive(line: str) -> bool:
    return bool(
        ESLINT_DISABLE.search(line)
        or ESLINT_INLINE.search(line)
        or TS_DIRECTIVE.search(line)
        or PRAGMA_DISABLE.match(line)
        or NULLABLE_DISABLE.match(line)
    )


def comment_start(line: str) -> int:
    """Index of the first // or /* that is not inside a string literal, or -1."""
    quote = ""
    index = 0
    while index < len(line):
        char = line[index]
        if quote:
            if char == "\\":
                index += 2
                continue
            if char == quote:
                quote = ""
        elif char in "\"'`":
            quote = char
        elif char == "/" and line[index + 1 : index + 2] in ("/", "*"):
            return index
        index += 1
    return -1


def clean_c_comment(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^\{?\s*(?:/\*+|//+|\*(?!/))", "", text)
    text = re.sub(r"\*+/\s*\}?\s*$", "", text)
    return text.strip()


def is_c_comment_line(line: str) -> bool:
    stripped = line.strip()
    return (
        stripped.startswith(("//", "/*", "{/*", "*"))
        or stripped.endswith(("*/", "*/}"))
    )


def trailing_c_comment(line: str, start: int = 0) -> str:
    index = comment_start(line[start:])
    return clean_c_comment(line[start + index :]) if index >= 0 else ""


def preceding_c_comment(lines: list[str], index: int) -> str:
    """The comment that ends on the line before `index`, joined; empty when that line is code,
    blank, or itself a suppression."""
    parts: list[str] = []
    cursor = index - 1
    while cursor >= 0:
        line = lines[cursor]
        if not is_c_comment_line(line) or is_c_directive(line):
            break
        parts.insert(0, clean_c_comment(line))
        cursor -= 1
    return " ".join(part for part in parts if part)


def block_comment_body(lines: list[str], index: int, start: int) -> str:
    """The text of the comment that opens at lines[index][start:], to its end."""
    line = lines[index]
    if line[start : start + 2] == "//":
        return line[start + 2 :]
    collected = [line[start + 2 :]]
    cursor = index
    while "*/" not in collected[-1] and cursor + 1 < len(lines):
        cursor += 1
        collected.append(lines[cursor])
    body = "\n".join(collected)
    return body.split("*/", 1)[0]


def eslint_reason(body: str) -> str:
    match = re.search(r"\s-{2,}(?:\s+(.*))?$", body, re.DOTALL)
    return " ".join((match.group(1) or "").split()) if match else ""


def scan_script(lines: list[str], is_eslint_config: bool) -> list[tuple[int, str]]:
    findings: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        number = index + 1

        match = ESLINT_DISABLE.search(line)
        if match:
            body = block_comment_body(lines, index, match.start())
            if not is_rationale(eslint_reason(body)):
                findings.append((number, "eslint-disable comment without a trailing '-- reason'"))

        match = ESLINT_INLINE.search(line)
        if match:
            body = block_comment_body(lines, index, match.start())
            configuration = re.split(r"\s-{2,}(?:\s|$)", body, maxsplit=1)[0]
            if SWITCHED_OFF.search(configuration) and not is_rationale(eslint_reason(body)):
                findings.append(
                    (number, "inline eslint comment turns a rule off without a trailing '-- reason'")
                )

        match = TS_DIRECTIVE.search(line)
        if match:
            body = block_comment_body(lines, index, match.start())
            after = body.split("@ts-" + match.group(1), 1)[1]
            if not is_rationale(after) and not is_rationale(preceding_c_comment(lines, index)):
                findings.append((number, f"@ts-{match.group(1)} without a rationale"))

    if is_eslint_config:
        findings.extend(scan_eslint_config(lines))
    return findings


RULE_OFF = re.compile(
    r"""(?:['"`][^'"`]+['"`]|[A-Za-z_$][\w$]*)\s*:\s*(?:\[\s*)?(?:(['"`])off\1|0(?![\w.]))\s*(?:[,\]}]|$)"""
)
PRETTIER_BINDING = re.compile(
    r"""(?:import\s+(?:\*\s+as\s+)?([A-Za-z_$][\w$]*)\s+from\s*|(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*)['"]eslint-config-prettier(?:/flat)?['"]"""
)


def scan_eslint_config(lines: list[str]) -> list[tuple[int, str]]:
    findings: list[tuple[int, str]] = []
    bindings: set[str] = set()
    binding_lines: set[int] = set()
    for index, line in enumerate(lines):
        match = PRETTIER_BINDING.search(line)
        if match:
            bindings.add(match.group(1) or match.group(2))
            binding_lines.add(index)

    for index, line in enumerate(lines):
        start = comment_start(line)
        code = line if start < 0 else line[:start]
        if not code.strip():
            continue

        def explained() -> bool:
            return is_rationale(trailing_c_comment(line)) or is_rationale(
                preceding_c_comment(lines, index)
            )

        if RULE_OFF.search(code) and not explained():
            findings.append((index + 1, "ESLint rule turned off without a rationale"))
        if index in binding_lines:
            continue
        if any(re.search(rf"(?<![\w$.]){re.escape(name)}(?![\w$])", code) for name in bindings):
            if not explained():
                findings.append(
                    (index + 1, "eslint-config-prettier turns rules off; its use has no rationale")
                )
        if re.search(r"\bdisableTypeChecked\b", code) and not explained():
            findings.append(
                (index + 1, "disableTypeChecked turns rules off; its use has no rationale")
            )
    return findings


def csharp_strings(text: str, start: int) -> tuple[int, list[tuple[int, int, str]]]:
    """From the position after an opening parenthesis: the index after the matching closing one,
    and the string literals met on the way as (start, end, value)."""
    literals: list[tuple[int, int, str]] = []
    depth = 1
    index = start
    while index < len(text) and depth > 0:
        char = text[index]
        raw = re.match(r'"{3,}', text[index:])
        if raw:
            fence = raw.group(0)
            end = text.find(fence, index + len(fence))
            end = len(text) if end < 0 else end
            literals.append((index, end + len(fence), text[index + len(fence) : end]))
            index = end + len(fence)
        elif char == "@" and text[index + 1 : index + 2] == '"':
            cursor = index + 2
            value = []
            while cursor < len(text):
                if text[cursor] == '"':
                    if text[cursor + 1 : cursor + 2] == '"':
                        value.append('"')
                        cursor += 2
                        continue
                    break
                value.append(text[cursor])
                cursor += 1
            literals.append((index, cursor + 1, "".join(value)))
            index = cursor + 1
        elif char == '"':
            cursor = index + 1
            value = []
            while cursor < len(text) and text[cursor] != '"':
                if text[cursor] == "\\":
                    cursor += 1
                value.append(text[cursor : cursor + 1])
                cursor += 1
            literals.append((index, cursor + 1, "".join(value)))
            index = cursor + 1
        else:
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
            index += 1
    return index, literals


def scan_csharp(text: str, lines: list[str]) -> list[tuple[int, str]]:
    findings: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        for pattern, what in (
            (PRAGMA_DISABLE, "#pragma warning disable"),
            (NULLABLE_DISABLE, "#nullable disable"),
        ):
            match = pattern.match(line)
            if match and not (
                is_rationale(trailing_c_comment(line, match.end()))
                or is_rationale(preceding_c_comment(lines, index))
            ):
                findings.append((index + 1, f"{what} without a rationale"))

    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line) + 1)
    for match in SUPPRESS_MESSAGE.finditer(text):
        index = text.count("\n", 0, match.start())
        line = lines[index]
        column = match.start() - offsets[index]
        start = comment_start(line)
        if 0 <= start < column:
            continue  # the attribute is only mentioned in a comment
        end, literals = csharp_strings(text, match.end())
        arguments = text[match.end() : end]
        justification = ""
        named = re.search(r"\bJustification\s*=", arguments)
        if named:
            # The literal that follows "Justification =", and any joined to it with "+".
            position = match.end() + named.end()
            for literal_start, literal_end, value in literals:
                if literal_start < position:
                    continue
                if text[position:literal_start].strip() not in ("", "+"):
                    break
                justification += value
                position = literal_end
        end_index = text.count("\n", 0, end)
        after = lines[end_index][max(0, end - offsets[end_index]) :] if end_index < len(lines) else ""
        if not (
            is_rationale(justification)
            or is_rationale(trailing_c_comment(after))
            or is_rationale(preceding_c_comment(lines, index))
        ):
            findings.append((index + 1, "SuppressMessage without a Justification"))
    return findings


# --------------------------------------------------------------------------------------------
# MSBuild files
# --------------------------------------------------------------------------------------------

XML_COMMENT = re.compile(r"<!--(.*?)-->", re.DOTALL)
MSBUILD_ELEMENT = re.compile(r"<\s*(NoWarn|WarningsNotAsErrors)(?=[\s/>])", re.IGNORECASE)
MSBUILD_ATTRIBUTE = re.compile(r"(?<![\w<])(NoWarn|WarningsNotAsErrors)\s*=\s*[\"']", re.IGNORECASE)


def scan_msbuild(text: str, lines: list[str]) -> list[tuple[int, str]]:
    def line_of(position: int) -> int:
        return text.count("\n", 0, position)

    comments = [
        (line_of(match.start()), line_of(match.end() - 1), " ".join(match.group(1).split()))
        for match in XML_COMMENT.finditer(text)
    ]
    masked = XML_COMMENT.sub(lambda match: re.sub(r"[^\n]", " ", match.group(0)), text)
    masked_lines = masked.split("\n")

    hits: list[tuple[int, int, str]] = []  # (line of the name, line the element starts on, what)
    for match in MSBUILD_ELEMENT.finditer(masked):
        index = line_of(match.start())
        hits.append((index, index, f"<{match.group(1)}>"))
    for match in MSBUILD_ATTRIBUTE.finditer(masked):
        opening = masked.rfind("<", 0, match.start())
        if opening < 0 or ">" in masked[opening : match.start()]:
            continue  # not inside a tag: element text, not an attribute
        hits.append((line_of(match.start()), line_of(opening), f"{match.group(1)} attribute"))

    suppression_lines = {start for _, start, _ in hits} | {name for name, _, _ in hits}
    findings: list[tuple[int, str]] = []
    for name_line, start_line, what in sorted(hits):
        explained = False
        for first, last, comment in comments:
            same_line = first <= name_line <= last or first <= start_line <= last
            above = (
                last == start_line - 1
                and not masked_lines[last].strip()
                and last not in suppression_lines
            )
            if (same_line or above) and is_rationale(comment):
                explained = True
                break
        if not explained:
            findings.append((name_line + 1, f"{what} without a rationale"))
    return findings


# --------------------------------------------------------------------------------------------
# .editorconfig and .globalconfig
# --------------------------------------------------------------------------------------------

BELOW_WARNING = r"(?:none|silent|suggestion|refactoring|hidden|info)"
SEVERITY_KEY = re.compile(
    rf"^\s*(dotnet_(?:analyzer_)?diagnostic\.[^=:\s]*severity)\s*[=:]\s*({BELOW_WARNING})\s*(?:[#;].*)?$",
    re.IGNORECASE,
)
SEVERITY_SUFFIX = re.compile(
    rf"^\s*([\w.\-]+)\s*=\s*[^#;:]*:\s*({BELOW_WARNING})\s*(?:[#;].*)?$", re.IGNORECASE
)


def is_low_severity(line: str) -> re.Match[str] | None:
    return SEVERITY_KEY.match(line) or SEVERITY_SUFFIX.match(line)


def scan_analyzer_config(lines: list[str]) -> list[tuple[int, str]]:
    findings: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        match = is_low_severity(line)
        if not match:
            continue
        trailing = re.search(r"[#;](.*)$", line)
        parts: list[str] = []
        cursor = index - 1
        while cursor >= 0 and lines[cursor].lstrip().startswith(("#", ";")):
            parts.insert(0, lines[cursor].lstrip().lstrip("#;").strip())
            cursor -= 1
        if not (
            (trailing and is_rationale(trailing.group(1))) or is_rationale(" ".join(parts))
        ):
            findings.append(
                (index + 1, f"{match.group(1)} set to {match.group(2).lower()} without a rationale")
            )
    return findings


# --------------------------------------------------------------------------------------------
# Files
# --------------------------------------------------------------------------------------------


def is_generated_migration(path: str, lines: list[str]) -> bool:
    if "Migrations" not in path.split("/")[:-1]:
        return False
    header = [line for line in lines if line.strip()][:5]
    return any("<auto-generated" in line for line in header)


def scan_file(path: str, text: str) -> list[tuple[int, str]]:
    name = path.rsplit("/", 1)[-1]
    lines = text.split("\n")
    if name.endswith(CSHARP):
        return [] if is_generated_migration(path, lines) else scan_csharp(text, lines)
    if name.endswith(MSBUILD):
        return scan_msbuild(text, lines)
    if name.endswith(ANALYZER_CONFIG):
        return scan_analyzer_config(lines)
    if name.endswith(SCRIPT):
        return scan_script(lines, bool(ESLINT_CONFIG.match(name)))
    return []


def git(root: str, *arguments: str) -> str:
    result = subprocess.run(
        ["git", "-C", root, *arguments], capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        sys.stderr.write(f"check-suppressions: git {' '.join(arguments)} failed in {root}:\n")
        sys.stderr.write(result.stderr)
        sys.exit(2)
    return result.stdout


def tracked_files(root: str) -> list[str]:
    prefix = git(root, "rev-parse", "--show-prefix").strip()
    files = []
    for path in git(root, "ls-files", "-z").split("\0"):
        if not path or SKIPPED_DIRECTORIES.intersection(path.split("/")[:-1]):
            continue
        if (prefix + path).startswith(FIXTURES) and not prefix.startswith(FIXTURES):
            continue
        files.append(path)
    return sorted(files)


def main(arguments: list[str]) -> int:
    if len(arguments) > 1 or (arguments and arguments[0] in ("-h", "--help")):
        sys.stderr.write("usage: check-suppressions.sh [ROOT]\n")
        return 2
    root = arguments[0] if arguments else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if not os.path.isdir(root):
        sys.stderr.write(f"check-suppressions: {root} is not a directory\n")
        return 2

    count = 0
    for path in tracked_files(root):
        full = os.path.join(root, path)
        if not path.endswith(CSHARP + MSBUILD + ANALYZER_CONFIG + SCRIPT) or not os.path.isfile(full):
            continue
        with open(full, encoding="utf-8-sig", errors="replace") as handle:
            text = handle.read().replace("\r\n", "\n")
        for number, what in sorted(set(scan_file(path, text))):
            print(f"{path}:{number}: {what}")
            count += 1

    if count:
        sys.stdout.flush()
        sys.stderr.write(
            f"check-suppressions: {count} suppression(s) without a rationale. Say why in one line"
            " (ten characters or more, not a TODO); see the header of scripts/check-suppressions.py"
            " for where the rationale goes.\n"
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
