#!/usr/bin/env python3
"""Invariant 8 guard: warnings are errors, and what switches a warning off says why.

Usage: check-suppressions.py [ROOT]

Scans the git-tracked files under ROOT (default: the repository this script lives in) and prints
one line per finding:

    <file>:<line>: <what was found>      (or <file>: <what was found> for a whole file or folder)

Exit code 0 when there is none (and nothing is printed), 1 when there is at least one, 2 for a
usage error. Run it through scripts/check-suppressions.sh.

There are two halves. The rationale half: a warning suppression must carry a one-line rationale.
The configuration half: the settings that make warnings errors and type checking strict may not
be switched off or weakened at all, and no comment excuses that.

Both lists are closed. A new kind of switch-off is added here together with a fixture case under
scripts/tests/check-suppressions/fixtures/.

What is a suppression, and where its rationale may stand:

  C# (.cs)
    #pragma warning disable, #nullable disable   a // comment on the same or the preceding line
    [SuppressMessage], [UnconditionalSuppressMessage]
                                                 a Justification string, or a comment as above
  MSBuild (.csproj, .props, .targets)
    <NoWarn>, <WarningsNotAsErrors>, and the same names as attributes (NoWarn on a
    PackageReference)                            an XML comment on the same or the preceding line
  .editorconfig, .globalconfig
    a severity of none, silent, or suggestion    a # or ; comment on the same or the preceding line
  JavaScript and TypeScript (.ts .tsx .mts .cts .js .jsx .mjs .cjs)
    eslint-disable, eslint-disable-line, eslint-disable-next-line, and an inline
    /* eslint rule: off */ comment               a trailing "-- reason" only
    @ts-ignore, @ts-expect-error, @ts-nocheck    text after the directive, or a comment on the
                                                 preceding line
  ESLint configuration (eslint.config.*, .eslintrc.js, .eslintrc.cjs)
    a rule set to 'off' or 0, and each use of eslint-config-prettier or disableTypeChecked
                                                 a comment on the same or the preceding line

A rationale is at least ten characters and is not a placeholder (TODO, FIXME, pending, n/a,
<Pending>, a bare "--"). A preceding line that is itself a suppression explains nothing. A comment
that runs over several lines counts as a whole.

The configuration half (nothing here is excused by a comment):

  The root Directory.Build.props
    must exist and set TreatWarningsAsErrors=true, EnableNETAnalyzers=true,
    EnforceCodeStyleInBuild=true, AnalysisLevel=latest, and Nullable=enable: each once, with no
    condition, in a PropertyGroup with no condition.
  Every other MSBuild file (*proj, .props, .targets)
    may not declare the first four of those, whatever the value, as an element or in an attribute
    or property list; <Nullable> may only be "enable".
  Every MSBuild file, the root one included
    may not declare RunAnalyzers, RunAnalyzersDuringBuild, CodeAnalysisTreatWarningsAsErrors,
    WarningLevel, AnalysisMode*, or AnalysisLevel<Category>.
  Directory.Build.props and Directory.Build.targets
    may exist only at the root.
  Command lines: .yml and .yaml under .github/, Dockerfile* and *.dockerfile, *.sh, *.rsp, and the
  "scripts" of every package.json
    no TreatWarningsAsErrors=false, -warnaserror- (-err-), -nowarn (-warnasmessage,
    -warnnotaserror, -noerr), NoWarn=, WarningsNotAsErrors=, an analyzer property set to false,
    AnalysisLevel=, AnalysisMode=, WarningLevel=, Nullable= other than enable, or a strict
    type-checking flag passed as false. A line that is only a # comment is not a command line.
  web/, extension/, e2e/
    each exists with a package.json and a tsconfig.json; the "lint" script has --max-warnings 0,
    no other --max-warnings value, and no "||".
    Every tsconfig*.json in them, and every file one of them lists under "references", resolves
    to "strict": true: set in the file, or inherited through "extends" from files in the
    repository (a package is not followed, so it counts as not strict). A file with "files": []
    and no "include" compiles nothing and is exempt. None of them, nor any file they extend, sets
    a strict-family flag or noUncheckedIndexedAccess to false. Comments and trailing commas are
    read as tsc reads them.

Not covered: properties a developer passes on their own command line, an analyzer package removed
from a project, and a tsconfig reached only through a -p or --project argument.

Not scanned: files under bin/, obj/, node_modules/, and dist/; this script's own fixtures when a
tree that contains them is scanned; and EF Core's generated files, which are the .cs files under a
Migrations folder that carry the "<auto-generated" header.
"""

from __future__ import annotations

import json
import os
import posixpath
import re
import subprocess
import sys

FIXTURES = "scripts/tests/check-suppressions/"
SKIPPED_DIRECTORIES = {"bin", "obj", "node_modules", "dist"}

CSHARP = (".cs",)
MSBUILD = (".csproj", ".props", ".targets")
ANALYZER_CONFIG = (".editorconfig", ".globalconfig")
SCRIPT = (".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs")
ESLINT_CONFIG = re.compile(r"^(eslint\.config\.(js|mjs|cjs|ts|mts|cts)|\.eslintrc\.(js|cjs))$")

MINIMUM_RATIONALE_LENGTH = 10
PLACEHOLDER = re.compile(r"^(todo|fixme|pending|n/a)", re.IGNORECASE)


def is_rationale(text: str) -> bool:
    """True when the text explains something: long enough, and not a placeholder."""
    # Leading punctuation ("-- ", ": ", "<") is decoration, not explanation.
    stripped = re.sub(r"^[^0-9A-Za-z]+", "", text.strip()).rstrip()
    if len(stripped) < MINIMUM_RATIONALE_LENGTH:
        return False
    return not PLACEHOLDER.match(stripped)


# --------------------------------------------------------------------------------------------
# C-style sources (C#, JavaScript, TypeScript)
# --------------------------------------------------------------------------------------------

ESLINT_DISABLE = re.compile(r"(?://|/\*)\s*eslint-disable(?:-next-line|-line)?(?![\w-])")
ESLINT_INLINE = re.compile(r"/\*\s*eslint\s+(?!-)")
TS_DIRECTIVE = re.compile(r"(?://+|/\*+)\s*@ts-(ignore|expect-error|nocheck)(?![\w-])")
PRAGMA_DISABLE = re.compile(r"^\s*#\s*pragma\s+warning\s+disable\b")
NULLABLE_DISABLE = re.compile(r"^\s*#\s*nullable\s+disable\b")
SUPPRESS_MESSAGE = re.compile(r"\b(?:Unconditional)?SuppressMessage(?:Attribute)?\s*\(")
SWITCHED_OFF = re.compile(r"""(?:(['"`])off\1|(?<![\w.])0(?![\w.]))""")


def is_c_directive(line: str) -> bool:
    return bool(
        ESLINT_DISABLE.search(line)
        or ESLINT_INLINE.search(line)
        or TS_DIRECTIVE.search(line)
        or PRAGMA_DISABLE.match(line)
        or NULLABLE_DISABLE.match(line)
    )


def comment_start(line: str) -> int:
    """Index of the first // or /* that is not inside a string literal, or -1."""
    quote = ""
    index = 0
    while index < len(line):
        char = line[index]
        if quote:
            if char == "\\":
                index += 2
                continue
            if char == quote:
                quote = ""
        elif char in "\"'`":
            quote = char
        elif char == "/" and line[index + 1 : index + 2] in ("/", "*"):
            return index
        index += 1
    return -1


def clean_c_comment(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^\{?\s*(?:/\*+|//+|\*(?!/))", "", text)
    text = re.sub(r"\*+/\s*\}?\s*$", "", text)
    return text.strip()


def is_c_comment_line(line: str) -> bool:
    stripped = line.strip()
    return (
        stripped.startswith(("//", "/*", "{/*", "*"))
        or stripped.endswith(("*/", "*/}"))
    )


def trailing_c_comment(line: str, start: int = 0) -> str:
    index = comment_start(line[start:])
    return clean_c_comment(line[start + index :]) if index >= 0 else ""


def preceding_c_comment(lines: list[str], index: int) -> str:
    """The comment that ends on the line before `index`, joined; empty when that line is code,
    blank, or itself a suppression."""
    parts: list[str] = []
    cursor = index - 1
    while cursor >= 0:
        line = lines[cursor]
        if not is_c_comment_line(line) or is_c_directive(line):
            break
        parts.insert(0, clean_c_comment(line))
        cursor -= 1
    return " ".join(part for part in parts if part)


def block_comment_body(lines: list[str], index: int, start: int) -> str:
    """The text of the comment that opens at lines[index][start:], to its end."""
    line = lines[index]
    if line[start : start + 2] == "//":
        return line[start + 2 :]
    collected = [line[start + 2 :]]
    cursor = index
    while "*/" not in collected[-1] and cursor + 1 < len(lines):
        cursor += 1
        collected.append(lines[cursor])
    body = "\n".join(collected)
    return body.split("*/", 1)[0]


def eslint_reason(body: str) -> str:
    match = re.search(r"\s-{2,}(?:\s+(.*))?$", body, re.DOTALL)
    return " ".join((match.group(1) or "").split()) if match else ""


def scan_script(lines: list[str], is_eslint_config: bool) -> list[tuple[int, str]]:
    findings: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        number = index + 1

        match = ESLINT_DISABLE.search(line)
        if match:
            body = block_comment_body(lines, index, match.start())
            if not is_rationale(eslint_reason(body)):
                findings.append((number, "eslint-disable comment without a trailing '-- reason'"))

        match = ESLINT_INLINE.search(line)
        if match:
            body = block_comment_body(lines, index, match.start())
            configuration = re.split(r"\s-{2,}(?:\s|$)", body, maxsplit=1)[0]
            if SWITCHED_OFF.search(configuration) and not is_rationale(eslint_reason(body)):
                findings.append(
                    (number, "inline eslint comment turns a rule off without a trailing '-- reason'")
                )

        match = TS_DIRECTIVE.search(line)
        if match:
            body = block_comment_body(lines, index, match.start())
            after = body.split("@ts-" + match.group(1), 1)[1]
            if not is_rationale(after) and not is_rationale(preceding_c_comment(lines, index)):
                findings.append((number, f"@ts-{match.group(1)} without a rationale"))

    if is_eslint_config:
        findings.extend(scan_eslint_config(lines))
    return findings


RULE_OFF = re.compile(
    r"""(?:['"`][^'"`]+['"`]|[A-Za-z_$][\w$]*)\s*:\s*(?:\[\s*)?(?:(['"`])off\1|0(?![\w.]))\s*(?:[,\]}]|$)"""
)
PRETTIER_BINDING = re.compile(
    r"""(?:import\s+(?:\*\s+as\s+)?([A-Za-z_$][\w$]*)\s+from\s*|(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*)['"]eslint-config-prettier(?:/flat)?['"]"""
)


def scan_eslint_config(lines: list[str]) -> list[tuple[int, str]]:
    findings: list[tuple[int, str]] = []
    bindings: set[str] = set()
    binding_lines: set[int] = set()
    for index, line in enumerate(lines):
        match = PRETTIER_BINDING.search(line)
        if match:
            bindings.add(match.group(1) or match.group(2))
            binding_lines.add(index)

    for index, line in enumerate(lines):
        start = comment_start(line)
        code = line if start < 0 else line[:start]
        if not code.strip():
            continue

        def explained() -> bool:
            return is_rationale(trailing_c_comment(line)) or is_rationale(
                preceding_c_comment(lines, index)
            )

        if RULE_OFF.search(code) and not explained():
            findings.append((index + 1, "ESLint rule turned off without a rationale"))
        if index in binding_lines:
            continue
        if any(re.search(rf"(?<![\w$.]){re.escape(name)}(?![\w$])", code) for name in bindings):
            if not explained():
                findings.append(
                    (index + 1, "eslint-config-prettier turns rules off; its use has no rationale")
                )
        if re.search(r"\bdisableTypeChecked\b", code) and not explained():
            findings.append(
                (index + 1, "disableTypeChecked turns rules off; its use has no rationale")
            )
    return findings


def csharp_strings(text: str, start: int) -> tuple[int, list[tuple[int, int, str]]]:
    """From the position after an opening parenthesis: the index after the matching closing one,
    and the string literals met on the way as (start, end, value)."""
    literals: list[tuple[int, int, str]] = []
    depth = 1
    index = start
    while index < len(text) and depth > 0:
        char = text[index]
        raw = re.match(r'"{3,}', text[index:])
        if raw:
            fence = raw.group(0)
            end = text.find(fence, index + len(fence))
            end = len(text) if end < 0 else end
            literals.append((index, end + len(fence), text[index + len(fence) : end]))
            index = end + len(fence)
        elif char == "@" and text[index + 1 : index + 2] == '"':
            cursor = index + 2
            value = []
            while cursor < len(text):
                if text[cursor] == '"':
                    if text[cursor + 1 : cursor + 2] == '"':
                        value.append('"')
                        cursor += 2
                        continue
                    break
                value.append(text[cursor])
                cursor += 1
            literals.append((index, cursor + 1, "".join(value)))
            index = cursor + 1
        elif char == '"':
            cursor = index + 1
            value = []
            while cursor < len(text) and text[cursor] != '"':
                if text[cursor] == "\\":
                    cursor += 1
                value.append(text[cursor : cursor + 1])
                cursor += 1
            literals.append((index, cursor + 1, "".join(value)))
            index = cursor + 1
        else:
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
            index += 1
    return index, literals


def scan_csharp(text: str, lines: list[str]) -> list[tuple[int, str]]:
    findings: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        for pattern, what in (
            (PRAGMA_DISABLE, "#pragma warning disable"),
            (NULLABLE_DISABLE, "#nullable disable"),
        ):
            match = pattern.match(line)
            if match and not (
                is_rationale(trailing_c_comment(line, match.end()))
                or is_rationale(preceding_c_comment(lines, index))
            ):
                findings.append((index + 1, f"{what} without a rationale"))

    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line) + 1)
    for match in SUPPRESS_MESSAGE.finditer(text):
        index = text.count("\n", 0, match.start())
        line = lines[index]
        column = match.start() - offsets[index]
        start = comment_start(line)
        if 0 <= start < column:
            continue  # the attribute is only mentioned in a comment
        end, literals = csharp_strings(text, match.end())
        arguments = text[match.end() : end]
        justification = ""
        named = re.search(r"\bJustification\s*=", arguments)
        if named:
            # The literal that follows "Justification =", and any joined to it with "+".
            position = match.end() + named.end()
            for literal_start, literal_end, value in literals:
                if literal_start < position:
                    continue
                if text[position:literal_start].strip() not in ("", "+"):
                    break
                justification += value
                position = literal_end
        end_index = text.count("\n", 0, end)
        after = lines[end_index][max(0, end - offsets[end_index]) :] if end_index < len(lines) else ""
        if not (
            is_rationale(justification)
            or is_rationale(trailing_c_comment(after))
            or is_rationale(preceding_c_comment(lines, index))
        ):
            findings.append((index + 1, "SuppressMessage without a Justification"))
    return findings


# --------------------------------------------------------------------------------------------
# MSBuild files
# --------------------------------------------------------------------------------------------

XML_COMMENT = re.compile(r"<!--(.*?)-->", re.DOTALL)
MSBUILD_ELEMENT = re.compile(r"<\s*(NoWarn|WarningsNotAsErrors)(?=[\s/>])", re.IGNORECASE)
MSBUILD_ATTRIBUTE = re.compile(r"(?<![\w<])(NoWarn|WarningsNotAsErrors)\s*=\s*[\"']", re.IGNORECASE)


def scan_msbuild(text: str, lines: list[str]) -> list[tuple[int, str]]:
    def line_of(position: int) -> int:
        return text.count("\n", 0, position)

    comments = [
        (line_of(match.start()), line_of(match.end() - 1), " ".join(match.group(1).split()))
        for match in XML_COMMENT.finditer(text)
    ]
    masked = XML_COMMENT.sub(lambda match: re.sub(r"[^\n]", " ", match.group(0)), text)
    masked_lines = masked.split("\n")

    hits: list[tuple[int, int, str]] = []  # (line of the name, line the element starts on, what)
    for match in MSBUILD_ELEMENT.finditer(masked):
        index = line_of(match.start())
        hits.append((index, index, f"<{match.group(1)}>"))
    for match in MSBUILD_ATTRIBUTE.finditer(masked):
        opening = masked.rfind("<", 0, match.start())
        if opening < 0 or ">" in masked[opening : match.start()]:
            continue  # not inside a tag: element text, not an attribute
        hits.append((line_of(match.start()), line_of(opening), f"{match.group(1)} attribute"))

    suppression_lines = {start for _, start, _ in hits} | {name for name, _, _ in hits}
    findings: list[tuple[int, str]] = []
    for name_line, start_line, what in sorted(hits):
        explained = False
        for first, last, comment in comments:
            same_line = first <= name_line <= last or first <= start_line <= last
            above = (
                last == start_line - 1
                and not masked_lines[last].strip()
                and last not in suppression_lines
            )
            if (same_line or above) and is_rationale(comment):
                explained = True
                break
        if not explained:
            findings.append((name_line + 1, f"{what} without a rationale"))
    return findings


# --------------------------------------------------------------------------------------------
# .editorconfig and .globalconfig
# --------------------------------------------------------------------------------------------

BELOW_WARNING = r"(?:none|silent|suggestion|refactoring|hidden|info)"
SEVERITY_KEY = re.compile(
    rf"^\s*(dotnet_(?:analyzer_)?diagnostic\.[^=:\s]*severity)\s*[=:]\s*({BELOW_WARNING})\s*(?:[#;].*)?$",
    re.IGNORECASE,
)
SEVERITY_SUFFIX = re.compile(
    rf"^\s*([\w.\-]+)\s*=\s*[^#;:]*:\s*({BELOW_WARNING})\s*(?:[#;].*)?$", re.IGNORECASE
)


def is_low_severity(line: str) -> re.Match[str] | None:
    return SEVERITY_KEY.match(line) or SEVERITY_SUFFIX.match(line)


def scan_analyzer_config(lines: list[str]) -> list[tuple[int, str]]:
    findings: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        match = is_low_severity(line)
        if not match:
            continue
        trailing = re.search(r"[#;](.*)$", line)
        parts: list[str] = []
        cursor = index - 1
        while cursor >= 0 and lines[cursor].lstrip().startswith(("#", ";")):
            parts.insert(0, lines[cursor].lstrip().lstrip("#;").strip())
            cursor -= 1
        if not (
            (trailing and is_rationale(trailing.group(1))) or is_rationale(" ".join(parts))
        ):
            findings.append(
                (index + 1, f"{match.group(1)} set to {match.group(2).lower()} without a rationale")
            )
    return findings


# --------------------------------------------------------------------------------------------
# Files
# --------------------------------------------------------------------------------------------


def is_generated_migration(path: str, lines: list[str]) -> bool:
    if "Migrations" not in path.split("/")[:-1]:
        return False
    header = [line for line in lines if line.strip()][:5]
    return any("<auto-generated" in line for line in header)


def scan_file(path: str, text: str) -> list[tuple[int, str]]:
    name = path.rsplit("/", 1)[-1]
    lines = text.split("\n")
    if name.endswith(CSHARP):
        return [] if is_generated_migration(path, lines) else scan_csharp(text, lines)
    if name.endswith(MSBUILD):
        return scan_msbuild(text, lines)
    if name.endswith(ANALYZER_CONFIG):
        return scan_analyzer_config(lines)
    if name.endswith(SCRIPT):
        return scan_script(lines, bool(ESLINT_CONFIG.match(name)))
    return []


# --------------------------------------------------------------------------------------------
# Configuration half: settings that may not be weakened, whatever comment accompanies them
# --------------------------------------------------------------------------------------------

Finding = tuple[str, int, str]  # (file, line or 0 when the finding is about the whole file, what)

ROOT_PROPS = "Directory.Build.props"
# What the root Directory.Build.props must set, each exactly once and unconditionally.
REQUIRED_IN_ROOT = {
    "TreatWarningsAsErrors": "true",
    "EnableNETAnalyzers": "true",
    "EnforceCodeStyleInBuild": "true",
    "AnalysisLevel": "latest",
    "Nullable": "enable",
}
# Declared nowhere but in the root file, whatever the value.
PINNED = {"treatwarningsaserrors", "enablenetanalyzers", "enforcecodestyleinbuild", "analysislevel"}
# Declared nowhere at all: each switches analysis off or lowers it.
SWITCHES = {
    "runanalyzers",
    "runanalyzersduringbuild",
    "codeanalysistreatwarningsaserrors",
    "warninglevel",
}
SCRIPT_PROJECTS = ("web", "extension", "e2e")
STRICT_FAMILY = (
    "strict",
    "noImplicitAny",
    "strictNullChecks",
    "strictFunctionTypes",
    "strictBindCallApply",
    "strictPropertyInitialization",
    "noImplicitThis",
    "useUnknownInCatchVariables",
    "alwaysStrict",
)
MAY_NOT_BE_FALSE = STRICT_FAMILY + ("noUncheckedIndexedAccess",)

MSBUILD_OPEN_TAG = re.compile(r"<([A-Za-z_][\w.\-]*)((?:\s[^<>]*?)?)(/?)>")
# The value is looked at, not consumed: in Properties="A=1;B=2" the names A and B are both found.
MSBUILD_ASSIGNMENT = re.compile(r"(?<![\w<$(.])([A-Za-z_]\w*)\s*=(?!=)(?=\s*[\"']?\s*([\w.\-]*))")
PROPERTY_GROUP = re.compile(r"<PropertyGroup((?:\s[^<>]*?)?)>")


def is_msbuild_file(path: str) -> bool:
    return path.lower().endswith(("proj", ".props", ".targets"))


def setting_kind(name: str) -> str:
    lower = name.lower()
    if lower in PINNED:
        return "pinned"
    if lower == "nullable":
        return "nullable"
    if lower in SWITCHES or lower.startswith(("analysismode", "analysislevel")):
        return "switch"
    return ""


def is_conditional(masked: str, position: int) -> str:
    """Why the element at `position` does not apply to every build, or an empty string."""
    before = masked[:position]
    groups = list(PROPERTY_GROUP.finditer(before))
    if not groups or before.rfind("</PropertyGroup") > groups[-1].start():
        return "is not inside a PropertyGroup"
    if groups[-1].group(1).strip():
        return "is inside a PropertyGroup that carries a condition or another attribute"
    for tag in ("Choose", "Target"):
        opened = len(re.findall(rf"<{tag}[\s>]", before))
        closed = len(re.findall(rf"</{tag}\s*>", before))
        if opened > closed:
            return f"is inside a <{tag}>"
    return ""


def scan_msbuild_settings(path: str, text: str) -> list[Finding]:
    masked = XML_COMMENT.sub(lambda match: re.sub(r"[^\n]", " ", match.group(0)), text)
    is_root = path == ROOT_PROPS
    findings: list[Finding] = []

    def line_of(position: int) -> int:
        return masked.count("\n", 0, position) + 1

    declared: dict[str, list[tuple[int, str, str]]] = {}  # lower name -> (position, attributes, value)
    for match in MSBUILD_OPEN_TAG.finditer(masked):
        name = match.group(1)
        kind = setting_kind(name)
        if not kind:
            continue
        end = masked.find("<", match.end())
        value = "" if match.group(3) else masked[match.end() : end if end >= 0 else None].strip()
        line = line_of(match.start())
        if kind == "switch":
            findings.append((path, line, f"<{name}> may not be declared: it switches analysis off or lowers it"))
        elif is_root:
            declared.setdefault(name.lower(), []).append((match.start(), match.group(2), value))
        elif kind == "pinned":
            findings.append(
                (path, line, f"<{name}> may be declared only in the root {ROOT_PROPS}, whatever its value")
            )
        elif value.lower() != "enable":
            findings.append((path, line, f"<Nullable>{value}</Nullable>: nullable checking may only be 'enable'"))

    for match in MSBUILD_ASSIGNMENT.finditer(masked):
        name = match.group(1)
        kind = setting_kind(name)
        if not kind or (kind == "nullable" and match.group(2).lower() == "enable"):
            continue
        findings.append(
            (
                path,
                line_of(match.start()),
                f"{name}={match.group(2)} in an attribute or a property list: the setting may not be"
                " changed this way",
            )
        )

    if is_root:
        for name, required in REQUIRED_IN_ROOT.items():
            declarations = declared.get(name.lower(), [])
            if not declarations:
                findings.append((path, 0, f"{name} is not set; the root {ROOT_PROPS} must set it to '{required}'"))
            for order, (position, attributes, value) in enumerate(declarations):
                line = line_of(position)
                if order > 0:
                    findings.append((path, line, f"{name} is declared more than once"))
                elif value.lower() != required:
                    findings.append((path, line, f"{name} is '{value}'; it must be '{required}'"))
                elif attributes.strip():
                    findings.append(
                        (path, line, f"{name} carries a condition or another attribute; it must be set unconditionally")
                    )
                elif is_conditional(masked, position):
                    findings.append((path, line, f"{name} {is_conditional(masked, position)}; it must be set unconditionally"))
    return findings


# Switch-offs on a command line. MSBuild reads its switches and property names without regard to
# case, so these do too.
COMMAND_LINE = [
    (
        re.compile(r"(?<![\w$(])(?:CodeAnalysis|MSBuild)?TreatWarningsAsErrors\s*=\s*[\"']?\s*false", re.IGNORECASE),
        "TreatWarningsAsErrors=false",
    ),
    (re.compile(r"(?<![\w.])[-/]{1,2}(?:warnaserror|err)-(?!\w)", re.IGNORECASE), "-warnaserror-"),
    (
        re.compile(r"(?<![\w.])[-/]{1,2}(?:nowarn|warnasmessage|warnnotaserror|noerr)(?![\w-])", re.IGNORECASE),
        "-nowarn",
    ),
    (re.compile(r"(?<![\w$(])(?:NoWarn|WarningsNotAsErrors)\s*=", re.IGNORECASE), "NoWarn="),
    (
        re.compile(
            r"(?<![\w$(])(?:EnableNETAnalyzers|EnforceCodeStyleInBuild|RunAnalyzers(?:DuringBuild)?)"
            r"\s*=\s*[\"']?\s*false",
            re.IGNORECASE,
        ),
        "analyzers switched off (EnableNETAnalyzers, EnforceCodeStyleInBuild, or RunAnalyzers =false)",
    ),
    (
        re.compile(r"(?<![\w$(])(?:AnalysisLevel\w*|AnalysisMode\w*|WarningLevel)\s*=", re.IGNORECASE),
        "analysis level changed (AnalysisLevel=, AnalysisMode=, or WarningLevel=)",
    ),
    (re.compile(r"(?<![\w$(])Nullable\s*=\s*[\"']?\s*(?!enable)\w", re.IGNORECASE), "Nullable= other than enable"),
    (
        re.compile(r"--(?:" + "|".join(MAY_NOT_BE_FALSE) + r")(?:\s+|=)[\"']?false", re.IGNORECASE),
        "a strict type-checking flag set to false",
    ),
]


def is_command_file(path: str) -> bool:
    name = path.rsplit("/", 1)[-1]
    lower = name.lower()
    return (
        lower.startswith("dockerfile")
        or lower.endswith((".dockerfile", ".sh", ".rsp"))
        or (path.startswith(".github/") and lower.endswith((".yml", ".yaml")))
    )


def command_line_findings(text: str) -> list[str]:
    return [label for pattern, label in COMMAND_LINE if pattern.search(text)]


def scan_command_file(path: str, text: str) -> list[Finding]:
    findings: list[Finding] = []
    for index, line in enumerate(text.split("\n")):
        if line.lstrip().startswith("#"):
            continue  # a comment line is not a command line; a comment after a command is scanned
        for label in command_line_findings(line):
            findings.append((path, index + 1, f"{label} on a command line"))
    return findings


def strip_jsonc(text: str) -> str:
    """JSON with comments and trailing commas, as plain JSON; line numbers are kept."""
    out: list[str] = []
    index = 0
    in_string = False
    while index < len(text):
        char = text[index]
        if in_string:
            out.append(char)
            if char == "\\":
                out.append(text[index + 1 : index + 2])
                index += 1
            elif char == '"':
                in_string = False
        elif char == '"':
            in_string = True
            out.append(char)
        elif text.startswith("//", index):
            end = text.find("\n", index)
            index = len(text) if end < 0 else end
            continue
        elif text.startswith("/*", index):
            end = text.find("*/", index + 2)
            end = len(text) if end < 0 else end + 2
            out.append(re.sub(r"[^\n]", " ", text[index:end]))
            index = end
            continue
        elif char == "," and next_token(text, index + 1) in ("}", "]"):
            out.append(" ")
        else:
            out.append(char)
        index += 1
    return "".join(out)


def next_token(text: str, index: int) -> str:
    """The first character at or after `index` that is not white space or part of a comment."""
    while index < len(text):
        if text[index].isspace():
            index += 1
        elif text.startswith("//", index):
            end = text.find("\n", index)
            index = len(text) if end < 0 else end
        elif text.startswith("/*", index):
            end = text.find("*/", index + 2)
            index = len(text) if end < 0 else end + 2
        else:
            return text[index]
    return ""


def key_line(plain: str, key: str) -> int:
    match = re.search(rf'"{re.escape(key)}"\s*:', plain, re.IGNORECASE)
    return plain.count("\n", 0, match.start()) + 1 if match else 0


def scan_package_scripts(path: str, text: str) -> tuple[list[Finding], dict[str, object] | None]:
    """Command-line findings in the scripts of one package.json, and its scripts block."""
    try:
        package = json.loads(text)
        scripts = package.get("scripts") if isinstance(package, dict) else None
    except ValueError:
        return [(path, 0, "cannot be read as JSON, so its scripts cannot be checked")], None
    if not isinstance(scripts, dict):
        return [], {}
    findings: list[Finding] = []
    for name, command in scripts.items():
        if isinstance(command, str):
            for label in command_line_findings(command):
                findings.append((path, key_line(text, name), f'{label} in the "{name}" script'))
    return findings, scripts


MAX_WARNINGS = re.compile(r"--max-warnings(?:\s+|=)(\S+)")


def check_lint_script(path: str, text: str, scripts: dict[str, object]) -> list[Finding]:
    lint = scripts.get("lint")
    if not isinstance(lint, str) or not lint.strip():
        return [(path, 0, 'the "lint" script is missing')]
    line = key_line(text, "lint")
    limits = MAX_WARNINGS.findall(lint)
    if not limits:
        return [(path, line, 'the "lint" script lacks --max-warnings 0')]
    findings: list[Finding] = []
    if any(limit.strip("\"'") != "0" for limit in limits):
        findings.append((path, line, 'the "lint" script sets --max-warnings to something other than 0'))
    if "||" in lint:
        findings.append((path, line, 'the "lint" script ignores a failure (||), which undoes --max-warnings 0'))
    return findings


class TypeScriptConfigs:
    """The tsconfig files of the script projects, read once each."""

    def __init__(self, root: str, tracked: set[str]) -> None:
        self.root = root
        self.tracked = tracked
        self.cache: dict[str, tuple[str, dict[str, object] | None]] = {}

    def exists(self, path: str) -> bool:
        return not path.startswith("..") and (
            path in self.tracked or os.path.isfile(os.path.join(self.root, path))
        )

    def load(self, path: str) -> tuple[str, dict[str, object] | None]:
        """The file as plain JSON text and as an object (None when it cannot be read)."""
        if path not in self.cache:
            plain, parsed = "", None
            try:
                with open(os.path.join(self.root, path), encoding="utf-8-sig") as handle:
                    plain = strip_jsonc(handle.read().replace("\r\n", "\n"))
                loaded = json.loads(plain)
                parsed = loaded if isinstance(loaded, dict) else None
            except (OSError, ValueError):
                pass
            self.cache[path] = (plain, parsed)
        return self.cache[path]

    def options(self, path: str) -> dict[str, object]:
        """compilerOptions with lower-case keys: tsc reads option names without regard to case."""
        parsed = self.load(path)[1] or {}
        options = parsed.get("compilerOptions")
        return {key.lower(): value for key, value in options.items()} if isinstance(options, dict) else {}

    def local_extends(self, path: str) -> list[str]:
        """The files this one extends that are in the repository; a package is not followed."""
        parsed = self.load(path)[1] or {}
        extends = parsed.get("extends")
        names = [extends] if isinstance(extends, str) else extends if isinstance(extends, list) else []
        found = []
        for name in names:
            if not isinstance(name, str) or not name.startswith("."):
                continue
            target = posixpath.normpath(posixpath.join(posixpath.dirname(path), name))
            for candidate in (target, target + ".json"):
                if self.exists(candidate) and not os.path.isdir(os.path.join(self.root, candidate)):
                    found.append(candidate)
                    break
        return found

    def references(self, path: str) -> list[str]:
        parsed = self.load(path)[1] or {}
        references = parsed.get("references")
        found = []
        for reference in references if isinstance(references, list) else []:
            name = reference.get("path") if isinstance(reference, dict) else None
            if not isinstance(name, str):
                continue
            target = posixpath.normpath(posixpath.join(posixpath.dirname(path), name))
            if os.path.isdir(os.path.join(self.root, target)):
                target = posixpath.join(target, "tsconfig.json")
            if self.exists(target):
                found.append(target)
        return found

    def strict(self, path: str, seen: tuple[str, ...] = ()) -> object:
        """The value of `strict` after the local `extends` chain, or None when nothing sets it."""
        if path in seen:
            return None
        own = self.options(path).get("strict")
        if own is not None:
            return own
        result = None
        for base in self.local_extends(path):  # a later entry overrides an earlier one
            inherited = self.strict(base, seen + (path,))
            if inherited is not None:
                result = inherited
        return result

    def compiles_nothing(self, path: str) -> bool:
        """A solution file: `"files": []` and no `include`; it only points at other configs."""
        parsed = self.load(path)[1] or {}
        return parsed.get("files") == [] and "include" not in parsed


def check_tsconfigs(root: str, files: list[str]) -> list[Finding]:
    configs = TypeScriptConfigs(root, set(files))
    # path -> whether the file must itself resolve to strict (a base reached only through
    # `extends` need not: the files that extend it are the ones checked).
    queue: dict[str, bool] = {
        path: True
        for path in files
        if path.split("/")[0] in SCRIPT_PROJECTS
        and "/" in path
        and re.fullmatch(r"tsconfig.*\.json", path.rsplit("/", 1)[-1], re.IGNORECASE)
    }
    findings: list[Finding] = []
    done: set[str] = set()
    while queue:
        path = sorted(queue)[0]
        must_be_strict = queue.pop(path)
        if path in done:
            continue
        done.add(path)
        plain, parsed = configs.load(path)
        if parsed is None:
            findings.append((path, 0, "cannot be read as JSON, so strict cannot be confirmed"))
            continue
        options = configs.options(path)
        for flag in MAY_NOT_BE_FALSE:
            if options.get(flag.lower()) is False:
                findings.append((path, key_line(plain, flag), f"{flag} is set to false"))
        for reference in configs.references(path):
            if reference not in done:
                queue[reference] = True
        for base in configs.local_extends(path):
            if base not in done:
                queue.setdefault(base, False)
        if not must_be_strict or options.get("strict") is False:
            continue
        if configs.compiles_nothing(path):
            continue
        if configs.strict(path) is not True:
            through = " through its local extends chain" if "extends" in parsed else ""
            findings.append((path, 0, f"strict does not resolve to true{through}; set strict: true"))
    return findings


def check_script_projects(root: str, files: list[str], read) -> list[Finding]:
    findings: list[Finding] = []
    tracked = set(files)
    for path in files:
        if path.rsplit("/", 1)[-1] != "package.json":
            continue
        text = read(path)
        if text is None:
            continue
        found, scripts = scan_package_scripts(path, text)
        findings.extend(found)
        if "/" in path and path.split("/")[0] in SCRIPT_PROJECTS and path.count("/") == 1 and scripts is not None:
            findings.extend(check_lint_script(path, text, scripts))

    for project in SCRIPT_PROJECTS:
        if not any(path.startswith(project + "/") for path in files):
            findings.append((project, 0, "the folder is missing; its lint and strict settings cannot be confirmed"))
            continue
        for required, what in (("package.json", "lint script"), ("tsconfig.json", "strict setting")):
            path = f"{project}/{required}"
            if path not in tracked or read(path) is None:
                findings.append((path, 0, f"the file is missing; the {what} cannot be confirmed"))
    findings.extend(check_tsconfigs(root, files))
    return findings


def check_configuration(root: str, files: list[str]) -> list[Finding]:
    def read(path: str) -> str | None:
        full = os.path.join(root, path)
        if not os.path.isfile(full):
            return None
        with open(full, encoding="utf-8-sig", errors="replace") as handle:
            return handle.read().replace("\r\n", "\n")

    findings: list[Finding] = []
    root_props = read(ROOT_PROPS) if ROOT_PROPS in files else None
    if root_props is None:
        findings.append(
            (
                ROOT_PROPS,
                0,
                "the file is missing; it must set "
                + ", ".join(f"{name} to '{value}'" for name, value in REQUIRED_IN_ROOT.items()),
            )
        )
    for path in files:
        name = path.rsplit("/", 1)[-1]
        if "/" in path and name.lower() in ("directory.build.props", "directory.build.targets"):
            findings.append(
                (path, 0, f"a nested {name} is not allowed: only the root one may exist")
            )
        text = read(path) if is_msbuild_file(path) or is_command_file(path) else None
        if text is None:
            continue
        if is_msbuild_file(path):
            findings.extend(scan_msbuild_settings(path, text))
        if is_command_file(path):
            findings.extend(scan_command_file(path, text))
    findings.extend(check_script_projects(root, files, read))
    return findings


def git(root: str, *arguments: str) -> str:
    result = subprocess.run(
        ["git", "-C", root, *arguments], capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        sys.stderr.write(f"check-suppressions: git {' '.join(arguments)} failed in {root}:\n")
        sys.stderr.write(result.stderr)
        sys.exit(2)
    return result.stdout


def tracked_files(root: str) -> list[str]:
    prefix = git(root, "rev-parse", "--show-prefix").strip()
    files = []
    for path in git(root, "ls-files", "-z").split("\0"):
        if not path or SKIPPED_DIRECTORIES.intersection(path.split("/")[:-1]):
            continue
        if (prefix + path).startswith(FIXTURES) and not prefix.startswith(FIXTURES):
            continue
        files.append(path)
    return sorted(files)


def main(arguments: list[str]) -> int:
    if len(arguments) > 1 or (arguments and arguments[0] in ("-h", "--help")):
        sys.stderr.write("usage: check-suppressions.sh [ROOT]\n")
        return 2
    root = arguments[0] if arguments else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if not os.path.isdir(root):
        sys.stderr.write(f"check-suppressions: {root} is not a directory\n")
        return 2

    files = tracked_files(root)
    count = 0
    for path in files:
        full = os.path.join(root, path)
        if not path.endswith(CSHARP + MSBUILD + ANALYZER_CONFIG + SCRIPT) or not os.path.isfile(full):
            continue
        with open(full, encoding="utf-8-sig", errors="replace") as handle:
            text = handle.read().replace("\r\n", "\n")
        for number, what in sorted(set(scan_file(path, text))):
            print(f"{path}:{number}: {what}")
            count += 1

    weakened = sorted(set(check_configuration(root, files)))
    for path, number, what in weakened:
        print(f"{path}:{number}: {what}" if number else f"{path}: {what}")

    sys.stdout.flush()
    if count:
        sys.stderr.write(
            f"check-suppressions: {count} suppression(s) without a rationale. Say why in one line"
            " (ten characters or more, not a TODO); see the header of scripts/check-suppressions.py"
            " for where the rationale goes.\n"
        )
    if weakened:
        sys.stderr.write(
            f"check-suppressions: {len(weakened)} setting(s) that switch off or weaken"
            " warnings-as-errors, analyzers, zero-warning linting, or strict type checking. No"
            " comment excuses these: restore the setting.\n"
        )
    return 1 if count or weakened else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
