#!/bin/sh
# Creates the GitHub release of a version tag with the extension zip and its checksum attached,
# or completes one that an earlier run left unfinished. It runs last in a release, after the
# images are tagged, and it never changes what an existing release already has.
#
#   scripts/release-github.sh --tag TAG --prerelease true|false --latest true|false --zip FILE
#
#   --tag         the pushed git tag, for example v1.4.2. It must exist in the local clone, with
#                 the earlier tags (the previous one is where the generated notes start).
#   --prerelease  whether the release is a pre-release  } both as printed by
#   --latest      whether the release is marked latest  } scripts/release-tags.sh
#   --zip         the packaged extension, named as it is to be attached
#                 (n8tracks-extension-1.4.2.zip). Its checksum is attached beside it as
#                 <name>.sha256: one line, "<sha256>  <name>", which `sha256sum -c` accepts.
#
# What it does:
#   - No release for the tag: creates it, named after the tag, with notes generated by GitHub and
#     both files attached. The notes of a stable release start from the previous stable tag; those
#     of a pre-release from the previous tag of any kind. "Previous" is the next lower version
#     among the tags contained in the tagged commit. The latest marker is set to exactly what
#     --latest says, never left to GitHub to decide.
#   - A release exists: its name, notes, pre-release flag, and latest marker are left as they
#     are, and so is every file it already has: nothing is replaced. A file that is missing is
#     attached. A missing checksum is computed from the zip the release already has, not from the
#     one built by this run; a zip attached beside an existing checksum must match it.
#   - A draft exists for the tag (a run was killed while creating the release): the missing files
#     are attached and the draft is published with the given flags. Its notes are kept.
#
# On success it prints these lines on stdout, suitable for $GITHUB_OUTPUT:
#
#   url=<the release's page>
#   created=true|false     false when the release already existed
#   attached=<names>       the files this run attached, separated by spaces; may be empty
#
# It uses `gh` (GH_TOKEN with `contents: write`; the repository is the clone's, or GH_REPO),
# `git`, and `jq`. Exit code 0 on success, 1 on a failure (the reason is on stderr), 2 for a usage
# error. scripts/tests/release-github/run.sh tests it against a stand-in `gh`.
set -eu
LC_ALL=C
export LC_ALL

say() {
  printf 'release-github: %s\n' "$1" >&2
}

usage() {
  say "$1"
  printf 'usage: release-github.sh --tag TAG --prerelease true|false --latest true|false --zip FILE\n' >&2
  exit 2
}

tag=
prerelease=
latest=
zip=
seen=

while [ $# -gt 0 ]; do
  case $1 in
    --tag | --prerelease | --latest | --zip)
      [ $# -ge 2 ] || usage "$1 needs a value"
      case " $seen " in
        *" $1 "*) usage "$1 was given twice" ;;
      esac
      seen="$seen $1"
      case $1 in
        --tag) tag=$2 ;;
        --prerelease) prerelease=$2 ;;
        --latest) latest=$2 ;;
        --zip) zip=$2 ;;
      esac
      shift 2
      ;;
    *) usage "unknown argument: $1" ;;
  esac
done

for required in --tag --prerelease --latest --zip; do
  case " $seen " in
    *" $required "*) ;;
    *) usage "$required is required" ;;
  esac
done

version_pattern='v[0-9]+\.[0-9]+\.[0-9]+(-[0-9a-z.-]+)?'
stable_pattern='v[0-9]+\.[0-9]+\.[0-9]+'

printf '%s\n' "$tag" | grep -Eq "^$version_pattern\$" ||
  usage "--tag \"$tag\" is not vX.Y.Z or vX.Y.Z-<prerelease>"
case $prerelease in
  true | false) ;;
  *) usage "--prerelease must be true or false, not \"$prerelease\"" ;;
esac
case $latest in
  true | false) ;;
  *) usage "--latest must be true or false, not \"$latest\"" ;;
esac
[ "$prerelease" = false ] || [ "$latest" = false ] ||
  usage "a pre-release cannot be marked latest"
[ -f "$zip" ] || usage "--zip \"$zip\" is not a file"

zip_name=$(basename "$zip")
sum_name="$zip_name.sha256"
printf '%s\n' "$zip_name" | grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]*\.zip$' ||
  usage "--zip \"$zip_name\" is not a plain file name ending in .zip"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

# checksum_file FILE: writes $work/$sum_name for the file, under the zip's name.
checksum_file() {
  printf '%s  %s\n' "$(sha256 "$1")" "$zip_name" >"$work/$sum_name"
}

# view: reads the release into $work/release.json. Sets $state to missing, draft, or published.
view() {
  if gh release view "$tag" --json isDraft,url,assets >"$work/release.json" 2>"$work/err"; then
    if [ "$(jq -r .isDraft "$work/release.json")" = true ]; then
      state=draft
    else
      state=published
    fi
  # Only this exact answer means "no such release"; anything else must not create one.
  elif grep -Fxq 'release not found' "$work/err"; then
    state=missing
  else
    sed 's/^/    /' "$work/err" >&2
    say "could not read the release $tag."
    exit 1
  fi
}

has_asset() {
  jq -e --arg name "$1" 'any(.assets[]; .name == $name)' "$work/release.json" >/dev/null
}

# previous_tag: prints the tag the generated notes start from, or nothing when there is none.
previous_tag() {
  # With this suffix setting git sorts v1.0.0-rc.1 before v1.0.0, as versions order.
  git -c versionsort.suffix=- tag --list 'v*' --merged "$tag" --sort=-v:refname >"$work/tags" || return 1
  grep -Ex "$version_pattern" "$work/tags" >"$work/versions" || true
  grep -Fxq -- "$tag" "$work/versions" || {
    say "the tag $tag is not in the local clone."
    return 1
  }
  if [ "$prerelease" = true ]; then
    wanted=$version_pattern
  else
    wanted=$stable_pattern
  fi
  # The list is highest first: the first wanted tag below this one.
  awk -v tag="$tag" 'found { print } $0 == tag { found = 1 }' "$work/versions" |
    grep -Ex "$wanted" | head -n 1 || true
}

attached=

view
if [ "$state" = missing ]; then
  start=$(previous_tag) || exit 1
  checksum_file "$zip"
  set -- "$tag" --title "$tag" --verify-tag --generate-notes "--latest=$latest"
  if [ -n "$start" ]; then
    set -- "$@" --notes-start-tag "$start"
    say "creating the release $tag, with notes from $start"
  else
    say "creating the release $tag, with notes from the beginning: no earlier tag to start from"
  fi
  if [ "$prerelease" = true ]; then
    set -- "$@" --prerelease
  fi
  # With files to attach, gh creates a draft, uploads, and only then publishes.
  if ! gh release create "$@" "$zip" "$work/$sum_name" >"$work/create.out" 2>"$work/err"; then
    sed 's/^/    /' "$work/err" >&2
    say "could not create the release $tag."
    exit 1
  fi
  created=true
  attached="$zip_name $sum_name"
else
  created=false
  say "the release $tag exists ($state): its notes and the files it has are left as they are"

  # attach FILE: never replaces; gh refuses a name the release already has.
  attach() {
    if ! gh release upload "$tag" "$1" >"$work/upload.out" 2>"$work/err"; then
      sed 's/^/    /' "$work/err" >&2
      say "could not attach $(basename "$1")."
      exit 1
    fi
    attached="$attached $(basename "$1")"
    say "attached $(basename "$1")"
  }

  # fetch NAME: downloads one file of the release into $work/published/.
  fetch() {
    mkdir -p "$work/published"
    if ! gh release download "$tag" --pattern "$1" --dir "$work/published" >/dev/null 2>"$work/err" ||
      [ ! -f "$work/published/$1" ]; then
      sed 's/^/    /' "$work/err" >&2
      say "could not download $1 from the release."
      exit 1
    fi
  }

  if has_asset "$zip_name"; then
    if ! has_asset "$sum_name"; then
      fetch "$zip_name"
      checksum_file "$work/published/$zip_name"
      attach "$work/$sum_name"
    fi
  elif has_asset "$sum_name"; then
    # Checked before attaching: a zip that does not match must not be published beside it.
    fetch "$sum_name"
    checksum_file "$zip"
    if ! cmp -s "$work/$sum_name" "$work/published/$sum_name"; then
      say "the release has $sum_name but no zip, and the zip built by this run does not match it."
      say "  Delete $sum_name from the release and run again: gh release delete-asset $tag $sum_name --yes"
      exit 1
    fi
    attach "$zip"
  else
    checksum_file "$zip"
    attach "$zip"
    attach "$work/$sum_name"
  fi
  attached=${attached# }

  if [ "$state" = draft ]; then
    if ! gh release edit "$tag" --draft=false "--prerelease=$prerelease" "--latest=$latest" \
      >"$work/edit.out" 2>"$work/err"; then
      sed 's/^/    /' "$work/err" >&2
      say "could not publish the draft release $tag."
      exit 1
    fi
    say "published the draft release $tag"
  fi
fi

# Read again: a published release's page is not the one the draft had.
view
if [ "$state" != published ] || ! has_asset "$zip_name" || ! has_asset "$sum_name"; then
  say "the release $tag is not published with both files after this run (state: $state)."
  exit 1
fi

printf 'url=%s\n' "$(jq -r .url "$work/release.json")"
printf 'created=%s\n' "$created"
printf 'attached=%s\n' "$attached"
