// <auto-generated />
using Microsoft.EntityFrameworkCore;

namespace Fixture.Persistence.Migrations
{
    [DbContext(typeof(FixtureContext))]
    partial class Handwritten
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }

        public string Lookup(string key) => null;
    }
}
