<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Old.Package" Version="1.0.0" NoWarn="NU1701" />
    <PackageReference Include="Other.Package"
                      Version="2.0.0"
                      NoWarn="NU1603" />
    <PackageReference Include="Third.Package" Version="3.0.0">
      <NoWarn>NU1608</NoWarn>
    </PackageReference>
  </ItemGroup>
</Project>
